### ISSUE TITLE
Options with special messages display [object Object] when selected

### ISSUE THREAD

**Issue by zarazan** [dalexj/lunch_time#7]
![Image of Problem](https://files.slack.com/files-pri/TCTRDABHR-FGS1ACPT5/screen_shot_2019-03-07_at_11.06.28_am.png)

**Comment by dalexj** [comment]
![image](https://user-images.githubusercontent.com/2790993/53979363-d86b6880-40ca-11e9-9366-d0cff42247c3.png)

**Comment by Ameobea** [comment]
How did this get through???  Where is the CI/CD pipeline to prevent this?

@dalexj I expected far better from you and your team.  We'll be holding a meeting internally to reconsider the continuation of your contract in the future.  In the meantime, please make sure that this issue is resolved as soon as possible.

**Comment by dalexj** [comment]
wont fix lol @Ameobea
